services:
  # Locally hosted database
  postgresql:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SD_DBNAME}
      POSTGRES_USER: ${SD_USER}
      POSTGRES_PASSWORD: ${SD_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shiny_network

  # The Shiny Server
  shiny_server:
    build:
      context: ./shiny-server
      dockerfile: Dockerfile
      args:
        SURVEYDOWN_GIT_URL: "https://github.com/JasonLocklin/survey-demo.git"
    restart: unless-stopped
    volumes:
      - ./shiny-logs:/var/log/shiny-server/ #Shiny errors
      - ./data-export:/srv/data_dumps # Survey data ends up here
    depends_on:
      - postgresql
    env_file:
      - .env
    ports:
      - "3838:3838" # use http://localhost:3838 locally for testing
    networks:
      - shiny_network

  # Web Server
  # This is the container existing mainly for demonstration purposes
  # Your IT or Web people will likely swap this for their own
  # web servers, with their regular firewall/SSO/authentication/etc.
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./data-export:/var/www/data-export
    depends_on:
      - shiny_server
    networks:
      - shiny_network


# Data volumes temporary data is stored between restarts
volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  shiny_network:
    driver: bridge
