
services:
  postgresql:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SD_DBNAME}
      POSTGRES_USER: ${SD_USER}
      POSTGRES_PASSWORD: ${SD_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shiny_network

  shiny_server:
    build:
      context: ./shiny-server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./shiny-logs:/var/log/shiny-server/
    depends_on:
      - postgresql
    env_file:
      - .env
    environment:
      SURVERYDOWN_GIT_URL: https://github.com/surveydown-dev/templates.git
    ports:
      - "3838:3838" # use http://localhost:3838 locally for testing
    networks:
      - shiny_network

  data_serializer:
    build:
      context: ./data-serializer
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data_dumps:/app/data_dumps # Mount a volume for output files
      - ./data-serializer-logs:/var/log/ # For cron job logs
    depends_on:
      - postgresql
    networks:
      - shiny_network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./data_dumps:/var/www/data_dumps 
    depends_on:
      - shiny_server
    networks:
      - shiny_network

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  shiny_network:
    driver: bridge
